export interface Product {
  id: number;
  name: string;
  category: string;
  price: string;
  image: string;
  stock: number;
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "A6S Auriculares Inalámbricos Negros",
    category: "Audio",
    price: "$9.000",
    image: "/products/a6s-auriculares-inalambricos-negros.png",
    stock: 1,
  },
  {
    id: 2,
    name: "Adaptador Americano",
    category: "Cargadores",
    price: "$2.000",
    image: "/products/adaptador-americano.png",
    stock: 3,
  },
  {
    id: 3,
    name: "Adaptador Europeo",
    category: "Cargadores",
    price: "$2.000",
    image: "/products/adaptador-europeo.png",
    stock: 2,
  },
  {
    id: 4,
    name: "Afnan 9 PM 100 Ml",
    category: "Perfumes",
    price: "$49.900",
    image: "/products/afnan-9-pm-100ml.png",
    stock: 1,
  },
  {
    id: 5,
    name: "Afnan 9AM 100 Ml",
    category: "Perfumes",
    price: "$19.000",
    image: "/products/afnan-9am-100ml.png",
    stock: 1,
  },
  {
    id: 6,
    name: "Afnan 9AM 30 Ml",
    category: "Perfumes",
    price: "$19.000",
    image: "/products/afnan-9am-30ml.png",
    stock: 1,
  },
  {
    id: 7,
    name: "Alargue 3 Enchufes 3 USB-A 1 USB-C",
    category: "Bazar",
    price: "$20.000",
    image: "/products/alargue-3-enchufes.png",
    stock: 1,
  },
  {
    id: 8,
    name: "ALVS 2i2 Eau de Parfum 30 Ml",
    category: "Perfumes",
    price: "$15.000",
    image: "/products/alvs-2i2-30ml.png",
    stock: 1,
  },
  {
    id: 9,
    name: "ALVS Invictus Eau de Toilette 30 Ml",
    category: "Perfumes",
    price: "$15.000",
    image: "/products/alvs-invictus-30ml.png",
    stock: 1,
  },
  {
    id: 10,
    name: "Antishock iPhone 17",
    category: "Fundas",
    price: "$3.000",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 11,
    name: "Antishock iPhone 17 Pro Max",
    category: "Fundas",
    price: "$3.000",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 12,
    name: "Antishock iPhone 16",
    category: "Fundas",
    price: "$2.500",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 13,
    name: "Antishock iPhone 14 Pro",
    category: "Fundas",
    price: "$2.500",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 14,
    name: "Antishock iPhone 16 Pro Max",
    category: "Fundas",
    price: "$2.500",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 15,
    name: "Antishock iPhone 15",
    category: "Fundas",
    price: "$2.500",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 16,
    name: "Antishock iPhone 13 Pro",
    category: "Fundas",
    price: "$2.500",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 17,
    name: "Antishock iPhone 13",
    category: "Fundas",
    price: "$2.500",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 18,
    name: "Antishock iPhone 15 Pro",
    category: "Fundas",
    price: "$2.500",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 19,
    name: "Antishock iPhone 16 Pro",
    category: "Fundas",
    price: "$2.500",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 20,
    name: "Antishock iPhone 17 Pro",
    category: "Fundas",
    price: "$3.000",
    image: "/products/antishock.png",
    stock: 1,
  },
  {
    id: 21,
    name: "Apple AirPods Max",
    category: "Audio",
    price: "$38.000",
    image: "/products/apple-airpods-max.png",
    stock: 1,
  },
  {
    id: 22,
    name: "Apple EarPods Lightning",
    category: "Audio",
    price: "$15.000",
    image: "/products/apple-earpods-lightning.png",
    stock: 1,
  },
  {
    id: 23,
    name: "Apple Leather Wallet",
    category: "Accesorios",
    price: "$9.000",
    image: "/products/apple-leather-wallet.png",
    stock: 1,
  },
  {
    id: 24,
    name: "Apple Lightning a USB-A 1m",
    category: "Cargadores",
    price: "$5.000",
    image: "/products/apple-lightning-usb-a-1m.png",
    stock: 2,
  },
  {
    id: 25,
    name: "Apple MagSafe Charger",
    category: "Cargadores",
    price: "$16.000",
    image: "/products/apple-magsafe-charger.png",
    stock: 3,
  },
  {
    id: 26,
    name: "Apple USB-C 20W",
    category: "Cargadores",
    price: "$15.000",
    image: "/products/apple-usb-c-20w.png",
    stock: 6,
  },
  {
    id: 27,
    name: "Apple USB-C Mallado 1m",
    category: "Cargadores",
    price: "$8.000",
    image: "/products/apple-usb-c-mallado-1m.png",
    stock: 9,
  },
  {
    id: 28,
    name: "Apple USB-C Mallado Cable 2m",
    category: "Cargadores",
    price: "$9.500",
    image: "/products/apple-usb-c-cable-2m.png",
    stock: 9,
  },
  {
    id: 29,
    name: "Apple USB-A a Lightning 1m",
    category: "Cargadores",
    price: "$9.500",
    image: "/products/apple-usb-a-lightning-1m.png",
    stock: 8,
  },
  {
    id: 30,
    name: "Apple Watch Ultra 2 49mm",
    category: "Relojes",
    price: "$60.000",
    image: "/products/apple-watch-ultra-49mm.png",
    stock: 1,
  },
  {
    id: 31,
    name: "Asad Lattafa Black 30 Ml",
    category: "Perfumes",
    price: "$15.000",
    image: "/products/asad-lattafa-30ml.png",
    stock: 1,
  },
  {
    id: 32,
    name: "Battery Pack Apple 5.000 mAh",
    category: "Cargadores",
    price: "$20.000",
    image: "/products/battery-pack-5000mah.png",
    stock: 1,
  },
  {
    id: 33,
    name: "Cable Ibek 3 en 1 Carga Rápida",
    category: "Cargadores",
    price: "$11.000",
    image: "/products/cable-ibek-3-en-1.png",
    stock: 2,
  },
  {
    id: 34,
    name: "Cable Ibek 4 en 1 Mallado",
    category: "Cargadores",
    price: "$10.000",
    image: "/products/cable-ibek-4-en-1.png",
    stock: 1,
  },
  {
    id: 35,
    name: "Cable Ibek USB-C 1m Mallado",
    category: "Cargadores",
    price: "$5.000",
    image: "/products/cable-ibek-usb-c-1m.png",
    stock: 1,
  },
  {
    id: 36,
    name: "Cable Ibek USB-C Carga Rápida",
    category: "Cargadores",
    price: "$5.000",
    image: "/products/cable-ibek-usb-c-carga-rapida.png",
    stock: 1,
  },
  {
    id: 37,
    name: "Cantimplora Stanley 780 Ml",
    category: "Bazar",
    price: "$18.900",
    image: "/products/cantimplora-stanley-780ml.png",
    stock: 1,
  },
  {
    id: 38,
    name: "Cargador 120W Xiaomi Carga Ultra Rápida",
    category: "Cargadores",
    price: "$7.000",
    image: "/products/cargador-120w.png",
    stock: 1,
  },
  {
    id: 39,
    name: "Cargador Ibek USB A+C",
    category: "Cargadores",
    price: "$9.000",
    image: "/products/cargador-ibek-usb-a-c.png",
    stock: 2,
  },
  {
    id: 40,
    name: "Cargador Hytoshy 125W Carga Ultra Rápida",
    category: "Cargadores",
    price: "$15.000",
    image: "/products/cargador-hytoshy-125w.png",
    stock: 2,
  },
  {
    id: 41,
    name: "Case Glass iPhone 13 Marrón",
    category: "Fundas",
    price: "$8.000",
    image: "/products/case-glass.png",
    stock: 2,
  },
  {
    id: 42,
    name: "Case Glass iPhone 13 Azul",
    category: "Fundas",
    price: "$8.000",
    image: "/products/case-glass.png",
    stock: 1,
  },
  {
    id: 43,
    name: "Case Glass iPhone 15 Negro",
    category: "Fundas",
    price: "$8.000",
    image: "/products/case-glass.png",
    stock: 1,
  },
  {
    id: 44,
    name: "Case Glass iPhone 16 Negro",
    category: "Fundas",
    price: "$8.000",
    image: "/products/case-glass.png",
    stock: 1,
  },
  {
    id: 45,
    name: "Case Glass iPhone 16 Azul",
    category: "Fundas",
    price: "$8.000",
    image: "/products/case-glass.png",
    stock: 1,
  },
  {
    id: 46,
    name: "Casio G-Shock",
    category: "Accesorios",
    price: "$22.000",
    image: "/products/casio-g-shock.png",
    stock: 1,
  },
  {
    id: 47,
    name: "Clear Case iPhone 14 Pro Max",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 48,
    name: "Clear Case iPhone 15",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 49,
    name: "Clear Case iPhone 12 Pro Max",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 50,
    name: "Clear Case iPhone 13/14",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 51,
    name: "Clear Case iPhone 11",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 52,
    name: "Clear Case iPhone 12/12 Pro",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 53,
    name: "Clear Case iPhone 14 Pro",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 54,
    name: "Clear Case iPhone 16 Pro",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 55,
    name: "Clear Case iPhone 15 Pro",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 56,
    name: "Clear Case iPhone 13 Pro",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 57,
    name: "Clear Case iPhone 15 Pro Max",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 58,
    name: "Clear Case iPhone 16 Pro Max",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 3,
  },
  {
    id: 59,
    name: "Clear Case iPhone 13 Pro Max",
    category: "Fundas",
    price: "$3.500",
    image: "/products/clear-case.png",
    stock: 1,
  },
  {
    id: 60,
    name: "Convertidor TV Box",
    category: "TV",
    price: "$32.500",
    image: "/products/convertidor-tv-box.png",
    stock: 1,
  },
  {
    id: 61,
    name: "Deleex Cargador de Pilas",
    category: "Bazar",
    price: "$11.000",
    image: "/products/deleex-cargador-pilas.png",
    stock: 1,
  },
  {
    id: 62,
    name: "Deleex Pilas AA Recargables",
    category: "Bazar",
    price: "$9.300",
    image: "/products/deleex-pilas-aa.png",
    stock: 1,
  },
  {
    id: 63,
    name: "Deleex Pilas AAA Recargables",
    category: "Bazar",
    price: "$10.200",
    image: "/products/deleex-pilas-aaa.png",
    stock: 3,
  },
  {
    id: 64,
    name: "Encendedor Chispero Eléctrico",
    category: "Bazar",
    price: "$8.000",
    image: "/products/encendedor-chispero-electrico.png",
    stock: 1,
  },
  {
    id: 65,
    name: "Encendedor Soplete Recargable",
    category: "Bazar",
    price: "$4.000",
    image: "/products/encendedor-soplete.png",
    stock: 7,
  },
  {
    id: 66,
    name: "Extractor de Puntos Negros Blanco",
    category: "Estética",
    price: "$11.500",
    image: "/products/extractor-puntos-negros.png",
    stock: 1,
  },
  {
    id: 67,
    name: "Extractor de Puntos Negros Rosa",
    category: "Estética",
    price: "$11.500",
    image: "/products/extractor-puntos-negros.png",
    stock: 1,
  },
  {
    id: 68,
    name: "Fuente 40-60W Apple",
    category: "Cargadores",
    price: "$25.000",
    image: "/products/fuente-apple-40-60w.png",
    stock: 2,
  },
  {
    id: 69,
    name: "Funda AirPods 3",
    category: "Accesorios",
    price: "$8.000",
    image: "/products/funda-airpods-3.png",
    stock: 2,
  },
  {
    id: 70,
    name: "Funda AirPods Pro 2",
    category: "Accesorios",
    price: "$8.000",
    image: "/products/funda-airpods-pro-2.png",
    stock: 3,
  },
  {
    id: 71,
    name: "Hawas Fire 100 Ml",
    category: "Perfumes",
    price: "$29.200",
    image: "/products/hawas-fire-100ml.png",
    stock: 1,
  },
  {
    id: 72,
    name: "His Confession 30 Ml",
    category: "Perfumes",
    price: "$15.000",
    image: "/products/his-confession-30ml.png",
    stock: 1,
  },
  {
    id: 73,
    name: "Jean Paul Gaultier Le Beau 100 Ml",
    category: "Perfumes",
    price: "$60.800",
    image: "/products/jean-paul-gaultier-le-beau-100ml.png",
    stock: 1,
  },
  {
    id: 74,
    name: "JBL Flip 6",
    category: "Audio",
    price: "$41.000",
    image: "/products/jbl-flip-6.png",
    stock: 1,
  },
  {
    id: 75,
    name: "JBL GO3",
    category: "Audio",
    price: "$26.000",
    image: "/products/jbl-go3.png",
    stock: 1,
  },
  {
    id: 76,
    name: "K9 Micrófono Inalámbrico Doble USB-C",
    category: "Audio",
    price: "$14.900",
    image: "/products/k9-microfono-inalambrico.png",
    stock: 1,
  },
  {
    id: 77,
    name: "Lámpara Mata Mosquitos",
    category: "Bazar",
    price: "$6.400",
    image: "/products/lampara-mata-mosquitos.png",
    stock: 1,
  },
  {
    id: 78,
    name: "Lattafa Badee Al Oud Sublime 30 Ml",
    category: "Perfumes",
    price: "$15.000",
    image: "/products/lattafa-badee-al-oud-sublime-30ml.png",
    stock: 1,
  },
  {
    id: 79,
    name: "Lattafa Ramz 100 Ml",
    category: "Perfumes",
    price: "$35.000",
    image: "/products/lattafa-ramz-100ml.png",
    stock: 1,
  },
  {
    id: 80,
    name: "Leather Case iPhone 13 Gris",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 81,
    name: "Leather Case iPhone 13 Marrón",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 82,
    name: "Leather Case iPhone 13 Pro Azul",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 83,
    name: "Leather Case iPhone 13 Pro Verde",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 84,
    name: "Leather Case iPhone 14 Marrón",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 85,
    name: "Leather Case iPhone 14 Negro",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 86,
    name: "Leather Case iPhone 15 Negro",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 87,
    name: "Leather Case iPhone 15 Violeta",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 88,
    name: "Leather Case iPhone 15 Marrón",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 89,
    name: "Leather Case iPhone 15 Pro Verde",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 90,
    name: "Leather Case iPhone 16 Negro",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 91,
    name: "Leather Case iPhone 16 Pro Azul",
    category: "Fundas",
    price: "$11.500",
    image: "/products/leather-case.png",
    stock: 1,
  },
  {
    id: 92,
    name: "MagSafe iPhone 16",
    category: "Fundas",
    price: "$4.500",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 93,
    name: "MagSafe iPhone 16 Pro",
    category: "Fundas",
    price: "$4.500",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 94,
    name: "MagSafe iPhone 15 Pro Max",
    category: "Fundas",
    price: "$4.500",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 95,
    name: "MagSafe iPhone 17",
    category: "Fundas",
    price: "$5.000",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 96,
    name: "MagSafe iPhone 17 Pro",
    category: "Fundas",
    price: "$5.000",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 97,
    name: "MagSafe iPhone 14 Pro Max",
    category: "Fundas",
    price: "$4.500",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 98,
    name: "MagSafe iPhone 13/14",
    category: "Fundas",
    price: "$4.500",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 99,
    name: "MagSafe iPhone 13 Pro Max",
    category: "Fundas",
    price: "$4.500",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 100,
    name: "MagSafe iPhone 15 Pro",
    category: "Fundas",
    price: "$4.500",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 101,
    name: "MagSafe iPhone 17 Pro Max",
    category: "Fundas",
    price: "$5.000",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 102,
    name: "MagSafe iPhone 13",
    category: "Fundas",
    price: "$4.500",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 103,
    name: "MagSafe iPhone 16 Pro Max",
    category: "Fundas",
    price: "$4.500",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 104,
    name: "MagSafe iPhone 15",
    category: "Fundas",
    price: "$4.500",
    image: "/products/magsafe.png",
    stock: 1,
  },
  {
    id: 105,
    name: "Malla Mesh Apple Watch",
    category: "Relojes",
    price: "$9.000",
    image: "/products/malla-mesh-apple-watch.png",
    stock: 1,
  },
  {
    id: 106,
    name: "Malla Xiaomi Mi Band 3/4",
    category: "Relojes",
    price: "$2.800",
    image: "/products/malla-xiaomi-mi-band-3-4.png",
    stock: 2,
  },
  {
    id: 107,
    name: "Molde Hielo para Quencher Violeta",
    category: "Bazar",
    price: "$16.000",
    image: "/products/molde-hielo-quencher.png",
    stock: 1,
  },
  {
    id: 108,
    name: "Molde Hielo para Quencher Verde",
    category: "Bazar",
    price: "$16.000",
    image: "/products/molde-hielo-quencher.png",
    stock: 1,
  },
  {
    id: 109,
    name: "Oryx Pilas AAA x4",
    category: "Bazar",
    price: "$750",
    image: "/products/oryx-pilas-aaa-x4.png",
    stock: 8,
  },
  {
    id: 110,
    name: "Perfumeros 10 Ml",
    category: "Perfumes",
    price: "$1.500",
    image: "/products/perfumeros-10ml.png",
    stock: 10,
  },
  {
    id: 111,
    name: "Pico Cebador",
    category: "Bazar",
    price: "$6.300",
    image: "/products/pico-cebador.png",
    stock: 1,
  },
  {
    id: 112,
    name: "Protector Cámara iPhone 14/14 Plus/15/15 Plus",
    category: "Vidrio Templado",
    price: "$2.500",
    image: "/products/protector-camara.png",
    stock: 2,
  },
  {
    id: 113,
    name: "Protector Cámara iPhone 16 Pro",
    category: "Vidrio Templado",
    price: "$2.500",
    image: "/products/protector-camara.png",
    stock: 2,
  },
  {
    id: 114,
    name: "Protector Cámara iPhone 17 Pro/17 Pro Max",
    category: "Vidrio Templado",
    price: "$2.500",
    image: "/products/protector-camara.png",
    stock: 2,
  },
  {
    id: 115,
    name: "Protector Cámara iPhone 13 Pro/13 Pro Max",
    category: "Vidrio Templado",
    price: "$2.500",
    image: "/products/protector-camara.png",
    stock: 2,
  },
  {
    id: 116,
    name: "Protector Cámara iPhone 11/12/12 Mini",
    category: "Vidrio Templado",
    price: "$2.500",
    image: "/products/protector-camara.png",
    stock: 2,
  },
  {
    id: 117,
    name: "Protector Cámara iPhone 11 Pro/11 Pro Max/12",
    category: "Vidrio Templado",
    price: "$2.500",
    image: "/products/protector-camara.png",
    stock: 2,
  },
  {
    id: 118,
    name: "Protector Cámara iPhone 14 Pro/14 Pro Max/16 Pro/16 Pro Max",
    category: "Vidrio Templado",
    price: "$2.500",
    image: "/products/protector-camara.png",
    stock: 2,
  },
  {
    id: 119,
    name: "Protector Cámara iPhone 16",
    category: "Vidrio Templado",
    price: "$2.500",
    image: "/products/protector-camara.png",
    stock: 1,
  },
  {
    id: 120,
    name: "Protector Cámara iPhone 17",
    category: "Vidrio Templado",
    price: "$2.500",
    image: "/products/protector-camara.png",
    stock: 1,
  },
  {
    id: 121,
    name: "Protector Pantalla Apple Watch Ultra Transparente",
    category: "Relojes",
    price: "$6.000",
    image: "/products/protector-apple-watch-ultra.png",
    stock: 1,
  },
  {
    id: 122,
    name: "Protector Pantalla Apple Watch Ultra Negro",
    category: "Relojes",
    price: "$6.000",
    image: "/products/protector-apple-watch-ultra.png",
    stock: 1,
  },
  {
    id: 123,
    name: "Receptor Bluetooth",
    category: "Accesorios",
    price: "$7.000",
    image: "/products/receptor-bluetooth.png",
    stock: 1,
  },
  {
    id: 124,
    name: "Reloj Lacoste",
    category: "Relojes",
    price: "$10.000",
    image: "/products/reloj-lacoste.png",
    stock: 1,
  },
  {
    id: 125,
    name: "Reloj Metálico Negro",
    category: "Relojes",
    price: "$14.000",
    image: "/products/reloj-metalico.png",
    stock: 1,
  },
  {
    id: 126,
    name: "Reloj Metálico Rojo",
    category: "Relojes",
    price: "$14.000",
    image: "/products/reloj-metalico.png",
    stock: 1,
  },
  {
    id: 127,
    name: "Silicone Case iPhone 15 Pro",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 5,
  },
  {
    id: 128,
    name: "Silicone Case iPhone 14 Pro Max",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 3,
  },
  {
    id: 129,
    name: "Silicone Case iPhone 15 Pro Max",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 5,
  },
  {
    id: 130,
    name: "Silicone Case iPhone 11",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 3,
  },
  {
    id: 131,
    name: "Silicone Case iPhone 13 Pro",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 5,
  },
  {
    id: 132,
    name: "Silicone Case iPhone 16",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 5,
  },
  {
    id: 133,
    name: "Silicone Case iPhone 17 Pro Max",
    category: "Fundas",
    price: "$9.500",
    image: "/products/silicone-case.png",
    stock: 5,
  },
  {
    id: 134,
    name: "Silicone Case iPhone 17",
    category: "Fundas",
    price: "$9.500",
    image: "/products/silicone-case.png",
    stock: 4,
  },
  {
    id: 135,
    name: "Silicone Case iPhone 12 Pro Max",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 1,
  },
  {
    id: 136,
    name: "Silicone Case iPhone 11 Pro",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 3,
  },
  {
    id: 137,
    name: "Silicone Case iPhone 12/12 Pro",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 1,
  },
  {
    id: 138,
    name: "Silicone Case iPhone 17 Pro",
    category: "Fundas",
    price: "$9.500",
    image: "/products/silicone-case.png",
    stock: 8,
  },
  {
    id: 139,
    name: "Silicone Case iPhone 14 Pro",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 1,
  },
  {
    id: 140,
    name: "Silicone Case iPhone 13 Pro Max",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 3,
  },
  {
    id: 141,
    name: "Silicone Case iPhone 13/14",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 19,
  },
  {
    id: 142,
    name: "Silicone Case iPhone 15",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 10,
  },
  {
    id: 143,
    name: "Silicone Case iPhone 16 Pro",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 7,
  },
  {
    id: 144,
    name: "Silicone Case iPhone 16 Pro Max",
    category: "Fundas",
    price: "$9.000",
    image: "/products/silicone-case.png",
    stock: 6,
  },
  {
    id: 145,
    name: "Soporte Laptop Reforzado Blanco",
    category: "Accesorios",
    price: "$9.000",
    image: "/products/soporte-laptop.png",
    stock: 2,
  },
  {
    id: 146,
    name: "Soporte Laptop Chica Rosa",
    category: "Accesorios",
    price: "$9.000",
    image: "/products/soporte-laptop-chica.png",
    stock: 1,
  },
  {
    id: 147,
    name: "Soporte para Moto Impermeable",
    category: "Accesorios",
    price: "$17.000",
    image: "/products/soporte-moto-impermeable.png",
    stock: 1,
  },
  {
    id: 148,
    name: "Space Color Case iPhone 16 Pro Transparente",
    category: "Fundas",
    price: "$5.100",
    image: "/products/space-color-case.png",
    stock: 1,
  },
  {
    id: 149,
    name: "Space Color Case iPhone 16 Pro Violeta",
    category: "Fundas",
    price: "$5.100",
    image: "/products/space-color-case.png",
    stock: 1,
  },
  {
    id: 150,
    name: "Space Color Case iPhone 16 Pro Amarillo",
    category: "Fundas",
    price: "$5.100",
    image: "/products/space-color-case.png",
    stock: 1,
  },
  {
    id: 151,
    name: "Termo Acero Inoxidable 1L",
    category: "Bazar",
    price: "$17.000",
    image: "/products/termo-acero-inoxidable-1l.png",
    stock: 2,
  },
  {
    id: 152,
    name: "Tiras Nasales x15",
    category: "Estética",
    price: "$4.000",
    image: "/products/tiras-nasales-x15.png",
    stock: 4,
  },
  {
    id: 153,
    name: "Tubos 35 Ml",
    category: "Perfumes",
    price: "$5.000",
    image: "/products/tubos-35ml.png",
    stock: 6,
  },
  {
    id: 154,
    name: "USB WiFi Antena",
    category: "Accesorios",
    price: "$9.000",
    image: "/products/usb-wifi-antena.png",
    stock: 1,
  },
  {
    id: 155,
    name: "Vidrio Templado 9D iPhone 11/XR",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 13,
  },
  {
    id: 156,
    name: "Vidrio Templado 9D iPhone 12/12 Pro",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 14,
  },
  {
    id: 157,
    name: "Vidrio Templado 9D iPhone 13 Pro Max",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 10,
  },
  {
    id: 158,
    name: "Vidrio Templado 9D iPhone 13/13 Pro/14",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 33,
  },
  {
    id: 159,
    name: "Vidrio Templado 9D iPhone 14 Pro",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 5,
  },
  {
    id: 160,
    name: "Vidrio Templado 9D iPhone 14 Pro Max",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 10,
  },
  {
    id: 161,
    name: "Vidrio Templado 9D iPhone 15 Pro Max",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 11,
  },
  {
    id: 162,
    name: "Vidrio Templado 9D iPhone 15/15 Pro",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 19,
  },
  {
    id: 163,
    name: "Vidrio Templado 9D iPhone 16",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 12,
  },
  {
    id: 164,
    name: "Vidrio Templado 9D iPhone 16 Pro",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 12,
  },
  {
    id: 165,
    name: "Vidrio Templado 9D iPhone 16 Pro Max",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 16,
  },
  {
    id: 166,
    name: "Vidrio Templado 9D iPhone 17",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 20,
  },
  {
    id: 167,
    name: "Vidrio Templado 9D iPhone 17 Pro",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 19,
  },
  {
    id: 168,
    name: "Vidrio Templado 9D iPhone 17 Pro Max",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 20,
  },
  {
    id: 169,
    name: "Vidrio Templado 9D iPhone XS/11 Pro",
    category: "Vidrio Templado",
    price: "$3.200",
    image: "/products/vidrio-9d.png",
    stock: 17,
  },
  {
    id: 170,
    name: "Vidrio Templado Antiespía iPhone 15/15 Pro",
    category: "Vidrio Templado",
    price: "$5.800",
    image: "/products/vidrio-antiespia.png",
    stock: 9,
  },
  {
    id: 171,
    name: "Vidrio Templado Antiespía iPhone 16 Pro",
    category: "Vidrio Templado",
    price: "$5.800",
    image: "/products/vidrio-antiespia.png",
    stock: 8,
  },
  {
    id: 172,
    name: "Vidrio Templado Antiespía iPhone X/11 Pro",
    category: "Vidrio Templado",
    price: "$5.800",
    image: "/products/vidrio-antiespia.png",
    stock: 7,
  },
  {
    id: 173,
    name: "Vidrio Templado Antiespía iPhone 16",
    category: "Vidrio Templado",
    price: "$5.800",
    image: "/products/vidrio-antiespia.png",
    stock: 8,
  },
  {
    id: 174,
    name: "Vidrio Templado Antiespía iPhone 14 Pro",
    category: "Vidrio Templado",
    price: "$5.800",
    image: "/products/vidrio-antiespia.png",
    stock: 10,
  },
  {
    id: 175,
    name: "Vidrio Templado Antiespía iPhone 12/12 Pro",
    category: "Vidrio Templado",
    price: "$5.800",
    image: "/products/vidrio-antiespia.png",
    stock: 2,
  },
  {
    id: 176,
    name: "Vidrio Templado Antiespía iPhone 13/13 Pro/14",
    category: "Vidrio Templado",
    price: "$5.800",
    image: "/products/vidrio-antiespia.png",
    stock: 11,
  },
  {
    id: 177,
    name: "Xerjoff Erba Pura 100ml",
    category: "Perfumes",
    price: "$85.500",
    image: "/products/xerjoff-erba-pura-100ml.png",
    stock: 1,
  },
  {
    id: 178,
    name: "Xiaomi Mi Compact Bluetooth Speaker 2 Blanco",
    category: "Audio",
    price: "$19.000",
    image: "/products/xiaomi-mi-compact-bluetooth-speaker-2.png",
    stock: 1,
  },
  {
    id: 179,
    name: "AirPods Pro 2da Generación",
    category: "Audio",
    price: "$26.500",
    image: "/products/airpods-pro-2da-generacion.png",
    stock: 0,
  },
  {
    id: 180,
    name: "Parlante JBL Go 4 RGB",
    category: "Audio",
    price: "$24.500",
    image: "/products/jbl-go-4-rgb.png",
    stock: 0,
  },
  {
    id: 181,
    name: "Bharara King Eau de Parfum 100 Ml",
    category: "Perfumes",
    price: "$62.600",
    image: "/products/bharara-king-100ml.png",
    stock: 0,
  },
  {
    id: 182,
    name: "Set de 7 Tuppers de Acrílico",
    category: "Bazar",
    price: "$28.600",
    image: "/products/set-7-tuppers-acrilico.png",
    stock: 0,
  },
  {
    id: 183,
    name: "Extensor de WiFi Xiaomi N300",
    category: "Accesorios",
    price: "$20.500",
    image: "/products/xiaomi-wifi-range-extender-n300.png",
    stock: 0,
  },
  {
    id: 184,
    name: "Luces para Bicicleta",
    category: "Accesorios",
    price: "$20.300",
    image: "/products/luces-bicicleta.png",
    stock: 2,
  },
];

// Alias para mantener compatibilidad si algún otro componente usa 'products'
export const products = MOCK_PRODUCTS;